### ISSUE TITLE
How do you store a fixed grid of "possible" points?

### ISSUE THREAD

**Issue by Darrah** [beloitcollegecomputerscience/Sona-Drawing#6]

**Comment by Darrah** [comment]
Probably storing the dots as an array of arrays (2D array).

**Comment by Darrah** [comment]
How do we arrange to handle designs of very large sizes? Create the largest imaginable array, or allow for creating a larger than "normal" array when necessary?

**Comment by Puyujiang** [comment]
Create an array, each element in the array contains two integer pointer to record the position and an arrray with three integer to record the status. 

Since the canvas is fixed, we dont allow user to change the size of the canvas at this stage. In that case, a fixed size array is enough. The size of the canvas can be changed in the code depend on the GUI team to decide what size is suitable for people to view the app.
